version: '3.7'

services:
  
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    environment:
      POSTGRES_USER: ${KONG_DB_USERNAME}
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD}
      POSTGRES_DB: ${KONG_DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - ${KONG_DB_PORT}:5432
    volumes:
    - persist_volume:/var/lib/postgresql/data
    networks:
    - kong-net

  #######################################
  # Kong database migration
  #######################################
  kong-migrations:
    entrypoint: sh -c "sleep 10 && kong migrations bootstrap -v"
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_DB_HOST}
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
    restart: on-failure
    networks:
    - kong-net

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_DB_HOST}
      KONG_PG_USER: ${KONG_DB_USERNAME}
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
      KONG_PROXY_ACCESS_LOG: ${KONG_PROXY_ACCESS_LOG}
      KONG_ADMIN_ACCESS_LOG: ${KONG_ADMIN_ACCESS_LOG}
      KONG_PROXY_ERROR_LOG: ${KONG_PROXY_ERROR_LOG}
      KONG_ADMIN_ERROR_LOG: ${KONG_ADMIN_ERROR_LOG}
      KONG_PROXY_LISTEN: ${KONG_PROXY_LISTEN}
      KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN}
    restart: on-failure
    ports:
    - $KONG_PROXY_PORT:8000
    - $KONG_PROXY_SSL_PORT:8443
    - $KONG_PROXY_ADMIN_API_PORT:8001
    - $KONG_PROXY_ADMIN_SSL_API_PORT:8444
    - $KONG_MANAGER_API_PORT:8002
    - $KONG_MANAGER_SSL_API_PORT:8445
    networks:
    - kong-net

volumes:
  persist_volume:

networks:
  kong-net: